In [1]:
import pandas as pd
import numpy as np


In [2]:
df = pd.read_csv("data/anime_with_synopsis.csv")

In [3]:
df1 = pd.read_csv("data/anime_with_synopsis.csv")

In [4]:
df1

MAL_ID                             Name    Score  \
0           1                     Cowboy Bebop     8.78   
1           5  Cowboy Bebop: Tengoku no Tobira     8.39   
2           6                           Trigun     8.24   
3           7               Witch Hunter Robin     7.27   
4           8                   Bouken Ou Beet     6.98   
...       ...                              ...      ...   
16209   48481  Daomu Biji Zhi Qinling Shen Shu  Unknown   
16210   48483                     Mieruko-chan  Unknown   
16211   48488  Higurashi no Naku Koro ni Sotsu  Unknown   
16212   48491      Yama no Susume: Next Summit  Unknown   
16213   48492                    Scarlet Nexus  Unknown   

                                                  Genres  \
0        Action, Adventure, Comedy, Drama, Sci-Fi, Space   
1                  Action, Drama, Mystery, Sci-Fi, Space   
2      Action, Sci-Fi, Adventure, Comedy, Drama, Shounen   
3      Action, Mystery, Police, Supernatural, Drama, ...   
4              Adventure, Fantasy, Shounen, Supernatural   
...                                                  ...   
16209                   Adventure, Mystery, Supernatural   
16210                       Comedy, Horror, Supernatural   
16211  Mystery, Dementia, Horror, Psychological, Supe...   
16212                   Adventure, Slice of Life, Comedy   
16213                                    Action, Fantasy   

                                               sypnopsis  
0      In the year 2071, humanity has colonized sever...  
1      other day, another bounty—such is the life of ...  
2      Vash the Stampede is the man with a $$60,000,0...  
3      ches are individuals with special powers like ...  
4      It is the dark century and the people are suff...  
...                                                  ...  
16209  No synopsis information has been added to this...  
16210  ko is a typical high school student whose life...  
16211          Sequel to Higurashi no Naku Koro ni Gou .  
16212                          New Yama no Susume anime.  
16213  Solar calendar year 2020: grotesque organisms ...  

[16214 rows x 5 columns]

In [5]:
df[df.sypnopsis.isna()]

MAL_ID                                               Name    Score  \
11451   34755  Kuma no Gakkou: Patissier Jackie to Ohisama no...  Unknown   
11469   34794                                Yukai na Animal Bus  Unknown   
13686   38475                                   Yuru Camp△ Movie  Unknown   
15025   40714  Youkai Watch Jam: Youkai Gakuen Y - N to no So...     6.28   
15747   42717                   Kaeru no Pickles: Kimochi no Iro  Unknown   
16056   44848                                        Iii Icecrin  Unknown   
16110   45731                   Argonavis from BanG Dream! Movie  Unknown   
16120   46095                          Vivy: Fluorite Eye's Song  Unknown   

                                           Genres sypnopsis  
11451                                Comedy, Kids       NaN  
11469                                Comedy, Kids       NaN  
13686                       Comedy, Slice of Life       NaN  
15025  Comedy, Demons, Kids, Supernatural, School       NaN  
15747                         Slice of Life, Kids       NaN  
16056                                        Kids       NaN  
16110                                       Music       NaN  
16120                                      Sci-Fi       NaN

In [6]:
df.dropna(inplace=True)

In [7]:
df[df.Genres.str.contains("Comedy", regex=False)]

MAL_ID                            Name    Score  \
0           1                    Cowboy Bebop     8.78   
2           6                          Trigun     8.24   
5          15                    Eyeshield 21     7.95   
6          16            Hachimitsu to Clover     8.06   
7          17      Hungry Heart: Wild Striker     7.59   
...       ...                             ...      ...   
16193   48413  Hataraku Maou-sama! 2nd Season  Unknown   
16199   48426  Kitarou Tanjou: Gegege no Nazo  Unknown   
16204   48456             SK∞: Crazy Rock Jam     6.52   
16210   48483                    Mieruko-chan  Unknown   
16212   48491     Yama no Susume: Next Summit  Unknown   

                                                  Genres  \
0        Action, Adventure, Comedy, Drama, Sci-Fi, Space   
2      Action, Sci-Fi, Adventure, Comedy, Drama, Shounen   
5                        Action, Sports, Comedy, Shounen   
6           Comedy, Drama, Josei, Romance, Slice of Life   
7                 Slice of Life, Comedy, Sports, Shounen   
...                                                  ...   
16193     Comedy, Demons, Supernatural, Romance, Fantasy   
16199              Comedy, Demons, Supernatural, Shounen   
16204                                     Comedy, Sports   
16210                       Comedy, Horror, Supernatural   
16212                   Adventure, Slice of Life, Comedy   

                                               sypnopsis  
0      In the year 2071, humanity has colonized sever...  
2      Vash the Stampede is the man with a $$60,000,0...  
5      Sena is like any other shy kid starting high s...  
6      Yuuta Takemoto, a sophomore at an arts college...  
7      Kyosuke Kano has lived under the shadow of his...  
...                                                  ...  
16193               Second season of Hataraku Maou-sama!  
16199  No synopsis information has been added to this...  
16204               cap of the first 9 episodes of SK∞ .  
16210  ko is a typical high school student whose life...  
16212                          New Yama no Susume anime.  

[5971 rows x 5 columns]

In [8]:
!pip install rake_nltk

In [9]:
from rake_nltk import Rake
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
def getKeyWords(text):
    r = Rake()
    r.extract_keywords_from_text(text)
    key_words_dict_scores = r.get_word_degrees()
    return list(key_words_dict_scores)

In [11]:
df['KW'] = df.sypnopsis.apply(getKeyWords)

In [12]:
df['Gen'] = df['Genres'].apply(getKeyWords)

In [13]:
df['Bags'] = df.Gen +  df.KW

In [14]:
df.columns

Index(['MAL_ID', 'Name', 'Score', 'Genres', 'sypnopsis', 'KW', 'Gen', 'Bags'], dtype='object')

In [15]:
anime_df = df[['MAL_ID', 'Bags']]

In [16]:
anime_df.MAL_ID

0            1
1            5
2            6
3            7
4            8
         ...  
16209    48481
16210    48483
16211    48488
16212    48491
16213    48492
Name: MAL_ID, Length: 16206, dtype: int64

In [17]:
def joinText(arr):
    return " ".join(arr)

In [18]:
anime_df['Bags'] = anime_df['Bags'].apply(joinText)

<ipython-input-18-609d65cc387a>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  anime_df['Bags'] = anime_df['Bags'].apply(joinText)


In [19]:
count = CountVectorizer(max_features=10)
count_matrix = count.fit_transform(anime_df['Bags'])
cosine_sim = cosine_similarity(count_matrix, count_matrix)
print(cosine_sim)

[[1.         0.61545745 0.80903983 ... 0.         0.52223297 0.34815531]
 [0.61545745 1.         0.73029674 ... 0.         0.23570226 0.47140452]
 [0.80903983 0.73029674 1.         ... 0.         0.77459667 0.25819889]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.52223297 0.23570226 0.77459667 ... 0.         1.         0.        ]
 [0.34815531 0.47140452 0.25819889 ... 0.         0.         1.        ]]


In [20]:
cosine_sim.shape

(16206, 16206)

In [22]:
cosine_df = pd.DataFrame(data=cosine_sim, index=anime_df['MAL_ID'], columns=anime_df['MAL_ID'])

In [26]:
cosine_df[5]

MAL_ID
1        0.615457
5        1.000000
6        0.730297
7        0.707107
8        0.166667
           ...   
48481    0.000000
48483    0.166667
48488    0.000000
48491    0.235702
48492    0.471405
Name: 5, Length: 16206, dtype: float64

In [175]:
def getScore(ani_id):
    ans = df1[df1['MAL_ID'] == ani_id]['Score']
    try:
        return float(ans)
    except:
        return 0

In [168]:
getScore(200)

7.48

In [197]:
def recommend(ani_id, data=cosine_df, filtering=True):
    ranking = data[ani_id].sort_values(ascending=False)
    ranking.drop(ani_id, axis=0, inplace=True)
    ranking_list = list(ranking.index)
    
    if filtering:
        output = []
        score = getScore(ani_id)
        for i in ranking_list:
            if (score - getScore(i) < 2):
                output.append(i)
            else:
                continue
            if len(output) == 10:
                return output
    else:
        output = ranking_list[:10]
    
            
    return output

In [198]:
def getName(i, df=df1):
    name = df1[df1['MAL_ID']==i]['Name'].values[0]
    return name

In [199]:
def listName(arr):
    list_name = []
    for i in arr:
        aniname = getName(i)
        list_name.append(aniname)
    return list_name

In [200]:
listName(recommend(5))

['Terra e... (TV)',
 'Higashi no Eden',
 'Hokuto no Ken 2',
 'Gunslinger Girl',
 'Mobile Suit Gundam Unicorn',
 'Megalo Box',
 'No Guns Life 2nd Season',
 'Schwarzesmarken',
 'Ashita no Joe 2',
 'Mobile Suit Gundam SEED']

In [201]:
listName(recommend(5114))

['Fullmetal Alchemist: The Sacred Star of Milos',
 'One Piece Film: Gold',
 'One Piece: Episode of Sabo - 3 Kyoudai no Kizuna Kiseki no Saikai to Uketsugareru Ishi',
 'One Piece: Episode of Nami - Koukaishi no Namida to Nakama no Kizuna',
 'One Piece Film: Strong World',
 'One Piece Film: Z',
 'One Piece',
 'InuYasha Movie 3: Tenka Hadou no Ken',
 'InuYasha Movie 2: Kagami no Naka no Mugenjo',
 'InuYasha Movie 4: Guren no Houraijima']

In [207]:
getName(5114)

'Fullmetal Alchemist: Brotherhood'

In [202]:
listName(recommend(11061))

['Hunter x Hunter',
 'Magi: Sinbad no Bouken',
 'Hunter x Hunter: Greed Island Final',
 'Log Horizon',
 'Wan Jie Xian Zong 2nd Season',
 'Dragon Ball Z Movie 14: Kami to Kami',
 'Yao Shen Ji Zhi Ying Yao Pian',
 'Doupo Cangqiong 3rd Season',
 'Goblin Slayer',
 'Wan Jie Xian Zong']

In [206]:
getName(11061)

'Hunter x Hunter (2011)'

In [196]:
cosine_df[11061].sort_values(ascending=False)

MAL_ID
136      1.0
22097    1.0
11061    1.0
7109     1.0
28045    1.0
        ... 
24627    0.0
24591    0.0
24577    0.0
24575    0.0
16183    0.0
Name: 11061, Length: 16206, dtype: float64